### ISSUE TITLE
communication-services-javascript-quickstarts\add-1-on-1-video-calling Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by typetrade** [Azure-Samples/communication-services-javascript-quickstarts#157]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> git clone https://github.com/Azure-Samples/communication-services-javascript-quickstarts.git
> npm i
>  npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map

### Any log messages given by the failure
>
PS D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling> npm i
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 624 packages, and audited 625 packages in 7s

30 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (1 low, 1 moderate, 7 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling>  npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\webpack\lib\util\createHash.js:135:53)    
    at NormalModule._initBuildHash (D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\webpack\lib\NormalModule.js:471:10)     
    at D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\Github\communication-services-javascript-quickstarts\add-1-on-1-video-calling\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.0

### Expected/desired behavior
> http://localhost:8080/ throw exception

### OS and Version?
> Windows 2022 Server

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jim-jigx** [comment]
This is apparently due to a security fix in new nodes. Discussion here: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported.
Workaround for me: export NODE_OPTIONS=--openssl-legacy-provider
